<div id="delivery-date">
    <strong><?php echo __('Delivery Date') ?></strong>
    <span class="price"><?=$block->getDeliveryDate() ?></span>
</div>
<div id="delivery-comment">
    <strong><?php echo __('Comment') ?>:</strong>
    <br/>
    <span class="price"><?=$block->getDeliveryComment() ?></span>
</div>
<?php 
$replacements 			=	$block->getReplacements();
$replacements_array 	=	array(
								''=>"",
								'contact-customer'=>__("Call me - If we can not reach you, we will leave out the unavailable item/s"),
								'we-decide'=>__('Let the personal shopper select the best available replacement.'),
								'ignore'=>__('Let the personal shopper select the best available replacement.'),
							);

if(isset($replacements_array[$replacements])){
	?>
	<div id="delivery-replacements">
		<strong><?php echo __('Replacements') ?>:</strong>
		<br/>
		<span class="price"><?=$replacements_array[$replacements];?></span>
	</div>
	<?php 
}
?>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            var element = $('#delivery-date').detach();
            $('.box-order-shipping-method').append(element);
            var element = $('#delivery-comment').detach();
            $('.box-order-shipping-method').append(element);
        }
    );
</script>