<?php
/**
 * @var $block IWD\CheckoutConnector\Block\Frame
 */
?>

<style>
    iframe{width:100%;min-height: 800px;}
</style>

<iframe id="iwdCheckoutFrame" src="<?php echo $block->getFrameUrl() ?>" frameborder="0" scrolling="no"></iframe>

<script type="text/x-magento-init">
    { "#iwdCheckoutFrame": { "IWD_CheckoutConnector/js/frameResizer": {"data": "bar"} } }
</script>

<script type="text/javascript">
    require(
        [
            'jquery',
        ],
        function($) {
            $(document).ready(function () {
                let changeUrlAction = function(event) {
                    if (event.data.changeUrlAction === 'edit_cart') {
                        window.location.href = '<?php echo $block->getEditCartUrl() ?>';
                    }
                    else if (event.data.changeUrlAction === 'login') {
                        window.location.href = '<?php echo $block->getLoginUrl() ?>';
                    }
                };

                let actionSuccess = function(event) {
                    if (event.data.actionSuccess) {
                        let successUrl = '<?php echo $block->getSuccessActionUrl() ?>',
                            successParams = event.data.actionSuccess;

                        window.location.href = successUrl+'?'+successParams;
                    }
                };

                if (window.addEventListener) {
                    window.addEventListener("message", changeUrlAction, false);
                    window.addEventListener("message", actionSuccess, false);
                } else if (window.attachEvent) {
                    window.attachEvent("onmessage", changeUrlAction);
                    window.attachEvent("onmessage", actionSuccess);
                }
            });
        }
    );
</script>
