<?php 
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$seller_exist= $helper->isSellerExist();
?>
<div>
	<?php if($seller_exist){ ?>
		<div class="fieldset">
			<h4 class="legend"><?php echo  __('Seller Request Panel') ?></h4>
				<div class="wk_emptymsg"><?php echo  __('Waiting for approval from admin') ?></div>
		</div>
	<?php }
	else { ?>
		<form action="<?php echo $block->getUrl('marketplace/account/becomesellerPost', ["_secure" => $this->getRequest()->isSecure()]) ?>" enctype="multipart/form-data" method="post" id="form-become-seller" data-mage-init='{"validation":{}}'>
			<?php echo $block->getBlockHtml('formkey')?>
			<div class="wk-mp-design">
				<fieldset class="fieldset info wk-mp-fieldset">
					<legend class="legend">
						<span><?php echo __('Seller Request Panel') ?></span>
						<button type="reset" class="button wk-mp-btn">
							<span><span><?php echo __('Cancel') ?></span></span>
						</button>
						<button type="submit" title="Save" class="button pay wk-mp-btn">
							<span>
								<span><?php echo  __('Save') ?></span>
							</span>
						</button>
					</legend>
					<div class="field required">
						<label class="label"><?php echo  __('Shop URL') ?></label>
						<?php
						if($helper->getProfileHintStatus() && $helper->getProfileHintShopurl()){?>
							<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProfileHintShopurl()?>"/>
						<?php
						} ?>
						<div class="control shop" id="wk-mp-become-seller-box-wrapper">
							<input type="text" class="required-entry wk_input_width" name="profileurl" id="profileurl" placeholder="<?php echo __("Please enter shop URL")?>"/>
							<div id="wk-load" class="no-display">
								<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/ajax-loader-tr.gif'); ?>" height="16px" width="16px"/>
							</div>
						</div>
					</div>
					<div class="field required">
						<input type="checkbox" class="required-entry" name="partnertype" id="partnertype"/>
						<label class="label"><?php echo  __('Do you want to become seller / vendor ?') ?></label>
					</div>
				</fieldset>
			</div>
		</form>
	<?php } ?>
</div>
<?php
$formData = [
    'ajaxSaveUrl' => $block->getUrl("marketplace/seller/usernameverify", ["_secure" => $this->getRequest()->isSecure()]),
    'successMessage' => __("available"),
    'errorMessage' => __("unavailable")
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>

<script type="text/x-magento-init">
    {
        "#form-become-seller": {
            "validation": {},
            "verifySellerShop": <?php /* @noEscape */ echo $serializedFormData; ?>
        }
    }
</script>