<div class="messages_wraper">
	<div class="row">
		<div class="col-sm-4">
			<div class="main_pro_sec men_pro_sec">
                <!-- <h3>Private Chats</h3> -->
                <ul class="main_pro_sec_ul nav nav-tabs">
                    <li class="active"><a href="#">John Doe</a></li>
					<li><a href="">Shankar</a></li>
                    <li><a href="#">John Doe</a></li>
					<li><a href="">Shankar</a></li>
                    <li><a href="#">John Doe</a></li>
					<li><a href="">Shankar</a></li>
					<li><a href="">Shankar</a></li>
                    <li><a href="#">John Doe</a></li>
					<li><a href="">Shankar</a></li>
                    <li><a href="#">John Doe</a></li>
					<li><a href="">Shankar</a></li>
                </ul>
            </div> <!-- main_pro_sec women_pro_sec -->
		</div>
		<div class="col-sm-8">
			<div class="message_chat">
				<div class="chat_row">
					<div class="chat_cont"><p>It is a long established page when looking at its layout.</p><p>fact that a reader will be distracted by the readable content of a page when looking at its layout.</p></div>
						<span>Friday, June 2016 at 5:05PM</span>
				</div>
				<div class="chat_row mybox">
					<div class="chat_cont"><p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p></div>
					<span>Friday, June 2016 at 5:05PM</span>
				</div>
				<div class="chat_row">
					<div class="chat_cont"><p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p></div>
					<span>Friday, June 2016 at 5:05PM</span>
				</div>
				<div class="chat_row mybox">
					<div class="chat_cont"><p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p><p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p></div>
					<span>Friday, June 2016 at 5:05PM</span>
				</div>
				<div class="chat_row">
					<div class="chat_cont"><p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p><p>It is a long established fact that a reader will be distracted by the readable.</p></div>
					<span>Friday, June 2016 at 5:05PM</span>
				</div>
				<div class="chat_row mybox">
					<div class="chat_cont"><p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p></div>
					<span>Friday, June 2016 at 5:05PM</span>
				</div>
			</div>
			<div class="input-group field">
		      <input type="text" class="form-control input-text" placeholder="Type Here...">
		      <span class="input-group-btn">
		        <button class="btn btn-primary" type="button"><i class="fa fa-send"></i></button>
		      </span>
		    </div><!-- /input-group -->
		</div>
	</div>
</div>