<div class="container">
<div class="footer content"> 
     
   <!-- <div class="f-left">
   <div class="middle-footer">
      <ul>
         <li><a href="<?php echo $this->getUrl('how-scappery-works');?>">How Scappery Works</a></li>
         <li><a href="<?php echo $this->getUrl('privacy-policy-cookie-restriction-mode');?>">Privacy Policy</a></li>
         <li><a href="<?php echo $this->getUrl('contact');?>">Contact Us</a></li>
         <li><a href="<?php echo $this->getUrl('press');?>">Press</a></li>
         <li><a href="<?php echo $this->getUrl('terms-conditions');?>">Terms & Conditions</a></li>
      </ul>
   </div> -->
   
   </div>

   <div class="row">
      <div class="col-md-4 col-sm-4">
         <ul>
            <li><a href="<?php echo $this->getUrl('terms-conditions');?>"><?php echo __('Terms & Conditions'); ?></a></li>
            <li><a href="<?php echo $this->getUrl('open-a-store-with-us');?>"><?php echo __('Open a Store with Us'); ?></a></li>
         </ul>
      </div>
      <div class="col-md-4 col-sm-4">
         <ul>
            <li><a href="<?php echo $this->getUrl('faq');?>"><?php echo __('FAQ'); ?></a></li>
            <li><a href="<?php echo $this->getUrl('contact');?>"><?php echo __('Contact Us'); ?></a></li>
         </ul>
      </div>
      <div class="col-md-4 col-sm-4">
         <ul>
            <li><a href="<?php echo $this->getUrl('about-us');?>"><?php echo __('About Us'); ?></a></li>
            <li><a href="<?php echo $this->getUrl('privacy-policy-cookie-restriction-mode');?>"><?php echo __('Privacy Policy'); ?></a></li>
         </ul>
      </div>
   </div>
   <div class="">
		<div class="col-md-4 col-sm-4">
		</div>
		<div class="col-md-4 col-sm-4">
			<div class="we-accept"> <img src="<?php echo $this->getViewFileUrl('images/visa-card.jpg'); ?>" alt="" />
				<img src="<?php echo $this->getViewFileUrl('images/master-card.jpg'); ?>" alt="" />
			</div>
		</div>
		<div class="col-md-4 col-sm-4">
			<div class="follow-method">
				<span><a href="javascript:void(0);" target="_blank"><img src='<?php echo $this->getViewFileUrl('images/fb-icon.png'); ?>' alt="Facebook"> </a></span>
				<span><a href="javascript:void(0);" target="_blank"><img src='<?php echo $this->getViewFileUrl('images/g-plus-icon.png'); ?>' alt="Google"> </a></span>
			</div>
		</div>
	</div>
   <!-- <div class="left-footer">
		<p>Copyright © 2018 <br/>
			Scappery.com, All rights reserved. 
		</p>
	</div> -->
   <div class="clearfix"></div>
</div>

<div class="copyright-content">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <div class="text-center">
               <p class="copyright-text"><?php echo __('Copyright © ').date("Y"); ?></p>
			   
            </div>
         </div>
      </div>
   </div>
</div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
			jQuery(".showcart").click(function(){
			jQuery("body").addClass("mini-cart");
	});		
	        jQuery("#btn-minicart-close").click(function(){
			jQuery("body").removeClass("mini-cart");
	});	
		
			
	});		 
</script>

<!--Start of Tawk.to Script
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5c7c2a9f3341d22d9ce71b92/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->
