<?php 
$partner=array();
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$partner = $helper->getSeller();
$isPartner = $helper->isSeller();
if($isPartner == 1){
	$filter_data_to = '';
    $filter_data_frm = '';
    $tr_id = '';	

    if(isset($_GET['tr_id'])){
        $tr_id = $_GET['tr_id'] != ""?$_GET['tr_id']:"";
    }
    if(isset($_GET['from_date'])){
        $filter_data_frm = $_GET['from_date'] != ""?$_GET['from_date']:"";
    }
    if(isset($_GET['to_date'])){
        $filter_data_to = $_GET['to_date'] != ""?$_GET['to_date']:"";
    } ?>
	<div class="wk-mp-design">
		<fieldset class="fieldset info wk-mp-fieldset">
			<legend class="legend"><span><?php echo __('Transaction List') ?></span></legend>
			<div class="grid">
				<div class="hor-scroll">
					<p><b><?php echo __('Remaining Transactions:') ?></b> <?php echo $block->Order->formatPrice($block->getRemainTotal());?></p>
					<form action="<?php echo $block->getCurrentUrl();?>" method="get">
						 <div class="no-more-tables"><table cellspacing="0" class="border wk-mp-list-table">
						    <thead>
						        <tr id="wk-mp-tr-heading">
						            <th><span><?php echo __('Transaction Id') ?></span></th>
						            <th><span><?php echo __('Date') ?></span></th>
						            <th><span>&nbsp;</span></th>
						        </tr>
						    </thead>
						    <tbody class="wk-mp-body">
						    	<tr>
						    		<td data-title="Transaction ID">
						    			<input type="text" class="input-text" name="tr_id" placeholder='<?php echo __('Search by Transaction Id') ?>' value="<?php echo $tr_id?>"/>
						    		</td>
						    		<td data-title="Date">
						    			<span class="wk-mp-td-span">
						    				<input name="from_date" id="special-from-date" class="input-text" value="<?php echo $filter_data_frm?>" type="text" placeholder='<?php echo __('Date From') ?>'/>
						    			</span>				    			
						    			<span class="wk-mp-td-span">
						    				<input name="to_date" id="special-to-date" class="input-text" value="<?php echo $filter_data_to?>" type="text" placeholder='<?php echo __('Date To') ?>'/>
						    			</span>
						    		</td>
						    		<td  data-title=" " class="wk-mp-td-last">
						    			<button class="button btn btn-lg btn-primary" title="Save" id="save-btn" type="submit">
											<span><?php echo __('Submit') ?></span>
										</button>
										<?php
										if($filter_data_frm){
											$fromdate = date_create($filter_data_frm);
		            						$filter_data_frm_post = date_format($fromdate, 'Y-m-d H:i:s');
		            					}else{
		            						$filter_data_frm_post = '';
		            					}
		            					if($filter_data_to){
		            						$todate = date_create($filter_data_to);
		            						$filter_data_to_post = date_format($todate, 'Y-m-d H:i:s');
		            					}else{
		            						$filter_data_to_post = '';
		            					}
										?>
										<a class="button btn btn-lg btn-info" href="<?php echo $block->getUrl('marketplace/transaction/downloadCsv', ['from_date'=>$filter_data_frm_post,'to_date'=>$filter_data_to_post, '_secure' => $this->getRequest()->isSecure()]);?>">
											<span><?php echo __('Download .CSV') ?></span>
										</a>
						    		</td>
						    	</tr>
						    </tbody>
						</table>
                        </div>
					</form>
					<?php 
					if(count($block->getAllTransaction())==0){ ?>		
						<div class="fieldset wk-mp-fieldset">
							<div class="wk-emptymsg">
								<?php echo __('No Transaction Available') ?>
							</div>
						</div>
						<?php 
					} else{ ?>
						<table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
						    <thead>
						        <tr class="wk-content">
						    		<th class="wk-first-td">
						    			<span class="label">
											<?php echo __('Date')?>
										</span>
						    		</th>
						    		<th>
						    			<span class="label">
											<?php echo __('Transaction Id')?>
										</span>
						    		</th>
						    		<th>
						    			<span class="label name">
											<?php echo __('Comment Message')?>
										</span>
						    		</th>
						    		<th>
						    			<span class="label">
											<?php echo __('Transaction Amount')?>
										</span>
						    		</th> 
						    		<th>
						    			<span class="label">
											<?php echo __('Action')?>
										</span>
						    		</th>   		
						    	</tr>
						    </thead>
						    <tbody>
						    	<?php 
						    	$i = 0;
								foreach($block->getAllTransaction() as $transactioncoll){
									$i++;
									?>
							    	<tr class="wk-row-view <?php echo $class = ($i == count($block->getAllTransaction()))? 'wk-last-tr':''?>">
							    		<td class="wk-first-td">
											<span class="label">
												<?php echo  $block->formatDate($transactioncoll->getCreatedAt())  ; ?>
											</span>	
							    		</td>
							    		<td>
											<span class="label">
												<?php echo $transactioncoll->getTransactionId(); ?>
											</span>	
							    		</td>								    		
										<td>
											<?php
											if($transactioncoll->getCustomNote()){
												$customnote = $transactioncoll->getCustomNote();
											}else{
												$customnote = __('None');
											}
											?>
											<span class="label name">
												<?php	
												 echo "<span class='bol'>". $customnote. "</span>" ;
											?>
											</span>	
										</td>
										<td>
											<span class="label price">
												<?php 
												echo $block->Order->formatPrice($transactioncoll->getTransactionAmount());
												?>
											</span>	
							    		</td>
							    		<td>
											<span class="label">
												<a href="<?php echo $block->getUrl('marketplace/transaction/view', ['id'=>$transactioncoll->getId(), '_secure' => $this->getRequest()->isSecure()])?>"><?php echo __('View');?></a>
											</span>	
							    		</td>
							    	</tr>
							    	<?php
							    }?>
						    </tbody>
						</table>
						<?php
					}?>
				</div>
			</div>	
			<?php if ($block->getPagerHtml()): ?>
		        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
		    <?php endif ?>	
		</fieldset>
	</div>
	<div class="buttons-set">
		<p class="back-link">
			<a href="javascript:;" onclick="javascript: window.history.back();" class="left btn btn-sm btn-primary">&laquo; <?php echo __('Back') ?></a>
		</p>
	</div>

	<script>
	    require([
	        "jquery",
	        "mage/mage",
        	'mage/calendar',
	        'prototype',
	        'domReady!'
	    ], function($){
	        $("#special-from-date").calendar({'dateFormat':'mm/dd/yy'});
			$("#special-to-date" ).calendar({'dateFormat':'mm/dd/yy'});
		});    
	</script>
	<?php 
}else{ ?>
	<h2 class="wk-mp-error_msg">
		<?php echo __("To Become Seller Please Contact to Admin."); ?>
	</h2>
	<?php
} ?>
