<?php
$partner=array();
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$partner=$block->getProfileDetail();
$seller_id=$partner['seller_id']; 

//$bestsellerProducts = $helper->getBestsellerProducts();

?>


<?php 

if($partner['shop_url']){
    
    
    $bestsellerProducts     =   $block->_getProductCollection();
    $bannerpic=$partner->getBannerPic()!=''?$partner->getBannerPic():"banner-image.png";
    $bannerpic=$helper->getMediaUrl().'avatar/'.$bannerpic;
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

    ?>
   <!--  <div class="collection-banner">
        <img src="<?php //echo $bannerpic; ?>" alt="no image"></img>
    </div> -->

    <!-- Left categories -->
    <?php //echo $this->getLayout()->createBlock("Webkul\Marketplace\Block\Sellercategory")->setTemplate("Webkul_Marketplace::sellerproductscategory.phtml")->toHtml();?>

    <div class="wk_mp_design">
        <div class="block block-account">   
            <div class="block-title">   
                <strong><span><h4><?php echo __("Top Selling Products") ?></h4></span></strong>
            </div>
        </div>
        <div class="page-products page-with-filter fieldset wk-mp-fieldset" <?php if($bestsellerProducts->count()){ echo 'style="padding: 0;"';}?>>
            <?php
            $_helper = $this->helper('Magento\Catalog\Helper\Output');
            ?>
            <?php if (!$bestsellerProducts->count()): ?>
                <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
            <?php else: ?>
                <?php echo $block->getToolbarHtml() ?>
                <?php echo $block->getAdditionalHtml() ?>
                <?php
                if ($block->getMode() == 'grid') {
                    $viewMode = 'grid';
                    $image = 'category_page_grid';
                    $showDescription = false;
                    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                } else {
                    $viewMode = 'list';
                    $image = 'category_page_list';
                    $showDescription = true;
                    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
                }
                /**
                 * Position for actions regarding image size changing in vde if needed
                 */
                $pos = $block->getPositioned();
                ?>
                <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
                    <?php $iterator = 1; ?>
                    <ol class="products list items product-items">
                        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                        <?php foreach ($bestsellerProducts as $_product): 
                        // echo "<pre/>";
                        // print_r($_product->getData());
                        // print_r(get_class_methods(get_class($_product))); die;
                        $_product = $objectManager->get('Magento\Catalog\Model\Product')->load($_product->getData()['product_id']);


                        ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <div class="product-item-info" data-container="product-grid">
                                <?php
                                $productImage = $block->getImage($_product, $image);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>
                                <?php // Product Image ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?php echo $productImage->toHtml(); ?>
                                </a>
                                <div class="product details product-item-details">
                                    <?php
                                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
                                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>

                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                            <!-- <div data-role="add-to-links" class="actions-secondary"<?php //echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>> -->
                                                
                                                <?php
                                                //$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                ?>
                                                <!-- <a href="#"
                                                   class="action tocompare"
                                                   title="<?php //echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   aria-label="<?php //echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ //echo $compareHelper->getPostDataParams($_product); ?>'
                                                   role="button">
                                                    <span><?php /* @escapeNotVerified */ //echo __('Add to Compare') ?></span>
                                                </a> -->
                                           <!--  </div> -->

                                            <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                <?php if ($_product->isSaleable()): ?>

                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#"
                                                       class="action towishlist fa fa-heart-o"
                                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist"
                                                       role="button">
                                                        <!-- <span><?php /* @escapeNotVerified */ //echo __('Add to Wish List') ?></span> -->
                                                    </a>
                                                <?php endif; ?>

                                                
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                                        <?php echo $block->getBlockHtml('formkey')?>
                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart  fa fa-shopping-cart">
                                                            <?php /* @escapeNotVerified */ //echo __('Add to Cart') ?>
                                                        </button>
                                                         <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
                                                           class="fa fa-search"
                                                           title="<?php echo $block->escapeHtml(__('View Item')); ?>"
                                                           aria-label="<?php echo $block->escapeHtml(__('View Item')); ?>"
                                                           role="button">
                                                        </a>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                            
                                        </div>
                                        <?php if ($showDescription):?>
                                            <div class="product description product-item-description">
                                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                                   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            <?php echo($iterator == count($bestsellerProducts)+1) ? '</li>' : '' ?>
                        <?php endforeach; ?>
                    </ol>
                </div>
                <?php echo $block->getToolbarHtml() ?>
                <?php if (!$block->isRedirectToCartEnabled()) : ?>
                    <script type="text/x-magento-init">
                    {
                        "[data-role=tocart-form], .form.map.checkout": {
                            "catalogAddToCart": {}
                        }
                    }
                    </script>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
<?php }  ?>
