<?php
// @codingStandardsIgnoreFile

/** @var $block \WeltPixel\Quickview\Block\Initialize */
?>
<script>
	var oquickview;
    requirejs(['jquery', 'weltpixel_quickview' ],
        function   ($, quickview) {
			oquickview	=	quickview;
            $(document).ready(function() {
                $(document).on('click', '.weltpixel-quickview', function() {
                    var prodUrl = $(this).attr('data-quickview-url');
                    if (prodUrl.length) {
                        quickview.displayContent(prodUrl);
                    }
                });
            });
        });
	
    window.weltpixel_quickview = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
	
	function openquickview($obj){
		var prodUrl = jQuery($obj).attr('data-quickview-url');
		if (prodUrl.length) {
			oquickview.displayContent(prodUrl);
		}
	}
</script>

