<?php 
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$isPartner = $helper->isSeller();
$product_hint_status = $helper->getProductHintStatus();
$objectManager 	= \Magento\Framework\App\ObjectManager::getInstance();
if($isPartner == 1){
	$rightseller = $helper->isRightSeller($this->getRequest()->getParam('id'));
	if($rightseller == 1){
		$currency_code = $helper->getCurrentCurrencyCode();
		$currency_symbol = $helper->getCurrencySymbol();

		$product_id=$this->getRequest()->getParam('id');
		$product_coll = $block->Product->load($product_id);
		?>
		<form action="<?php echo $block->getUrl('marketplace/product/save', ['_secure' => $this->getRequest()->isSecure()]) ?>" enctype="multipart/form-data" method="post" id="edit-product" data-form="edit-product">
			<div class="wk-mp-design" id="wk-bodymain">
				<fieldset class="fieldset info wk-mp-fieldset">
					<legend class="legend">
						<span><?php echo __('Edit Product') ?></span>
						<button type="reset" class="button wk-mp-btn">
					<span><span><?php echo __('Reset') ?></span></span>
				</button>
				<button class="button wk-mp-btn" title="<?php echo __('Save') ?>" type="submit" id="save-btn">
					<span><span><?php echo __('Save') ?></span></span>
				</button>
					</legend>			
					<?php echo $block->getBlockHtml('formkey')?>
					<input id="product_type_id" name="type" type="hidden" value="<?php echo $product_coll['type_id']?>">					
					<input type="hidden" name="id" value="<?php echo $product_id; ?>" />
					<input type="hidden" name="product_id" value="<?php echo $product_id; ?>" />
					<input type="hidden"  name="product[website_ids][]" id="website" value="<?php echo $product_coll->getStore()->getWebsiteId()?>" title="wstoreids" class="" />	
					<div class="field required">
						<label class="label"><?php echo __('Attribute Set') ?>:</label>
						<div class="control">
							<select name="set" id="attribute-set-id"  class="required-entry">
							<?php foreach($helper->getAllowedSets() as $set) {?>
								<option value="<?php echo $set['value'] ?>" <?php if($product_coll['attribute_set_id']==$set['value']){ ?> selected="selected" <?php } ?>><?php echo $set['label']?></option>
							<?php } ?>
							</select>
						</div>
					</div>		
					<div class="field">
						<label class="label"><?php echo __('Product Category') ?>:</label>
						<?php
						if($product_hint_status && $helper->getProductHintCategory()){?>
							<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintCategory() ?>"/>
						<?php
						} ?>
						<div class="wk-field wk-category">
							<div class="wk-for-validation">
								<div id="wk-category-label"><?php echo __("CATEGORIES"); ?></div>
								<?php 
								$categories = $product_coll->getCategoryIds();
								$cat_ids=implode(",",$categories);
								foreach ($categories as $value) {
									?>
									<input type="hidden" name="product[category_ids][]" value="<?php echo $value; ?>" id="wk-cat-hide<?php echo $value; ?>"/>
									<?php
								}
								?>
		            			<?php
		            			if($helper->getAllowedCategoryIds()){
		            				$storeconfig_catids = explode(',',trim($helper->getAllowedCategoryIds()));
		            				foreach($storeconfig_catids as $storeconfig_catid)	{
		            					$cat_model = $block->Category->load($storeconfig_catid); 
		            					if(isset($cat_model["entity_id"]) && $cat_model["entity_id"]){
			            					?>
											<div class="wk-cat-container">
												</span><span class="wk-foldersign"></span>
												<span class="wk-elements wk-cat-name"><?php echo $cat_model->getName() ?></span>
												<?php 
												if(in_array($cat_model["entity_id"],$categories)) {?>
													<input class="wk-elements" type="checkbox" name="product[category_ids][]" value=<?php echo $cat_model['entity_id'] ?> checked />
												 	<?php 
												}else { ?>
													<input class="wk-elements" type="checkbox" name="product[category_ids][]" value='<?php echo $cat_model['entity_id'] ?>'/>
												<?php 
												} ?>
											</div> 
									   		<?php 
									   	}
		            				}
		            			}else{
			            			$count = 0;
									$category_helper = $this->helper('Magento\Catalog\Helper\Category');
									$category_model = $block->Category;
									$_categories = $category_helper->getStoreCategories();
									foreach($_categories as $_category)	{
										$count++;
									 	if(count($category_model->getAllChildren($category_model->load($_category['entity_id'])))-1 > 0){ ?>
											<div class="wk-cat-container" style="margin-left:0px;">
												<span class="wk-plus">
												</span><span class="wk-foldersign"></span>
												<span class="wk-elements wk-cat-name"><?php echo $_category->getName() ?></span>
												<?php 
												if(in_array($_category["entity_id"],$categories)) {?>
													<input class="wk-elements" type="checkbox" name="product[category_ids][]" value=<?php echo $_category['entity_id'] ?> checked />
												 	<?php 
												}else { ?>
													<input class="wk-elements" type="checkbox" name="product[category_ids][]" value='<?php echo $_category['entity_id'] ?>'/>
												<?php 
												} ?>
											</div>
											<?php
										}else { ?>
											<div class="wk-cat-container">
												</span><span class="wk-foldersign"></span>
												<span class="wk-elements wk-cat-name"><?php echo $_category->getName() ?></span>
												<?php 
												if(in_array($_category["entity_id"],$categories)) {?>
													<input class="wk-elements" type="checkbox" name="product[category_ids][]" value=<?php echo $_category['entity_id'] ?> checked />
												 	<?php 
												}else { ?>
													<input class="wk-elements" type="checkbox" name="product[category_ids][]" value='<?php echo $_category['entity_id'] ?>'/>
												<?php 
												} ?>
											</div> 
									   		<?php 
										}
								    } 
							    } ?>
							</div>
						</div>
					</div>
					<div class="field required">
						<label class="label"><?php echo __('Product Name') ?>:</label>
						<?php
						if($product_hint_status && $helper->getProductHintName()){?>
							<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintName() ?>"/>
						<?php
						} ?>
						<div class="control">
							<input type="text" class="required-entry input-text" name="product[name]" id="name" value="<?php echo $product_coll->getName(); ?>"/>
						</div>
					</div>
					<div class="field required">
						<label class="label"><?php echo __('Description') ?>:</label>
						<?php
						if($product_hint_status && $helper->getProductHintDesc()){?>
							<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintDesc() ?>"/>
						<?php
						} ?>
						<div class="control">
							<textarea name="product[description]" class="required-entry input-text" id="description" rows="5" cols="75" ><?php echo $product_coll->getDescription(); ?></textarea>							
						    <?php /* <script>
								require([
								    'jquery',
								    'mage/adminhtml/wysiwyg/tiny_mce/setup'
								], function(jQuery){

									var config = '<?php echo $block->getWysiwygConfig() ?>',
									    editor;

									jQuery.extend(config, {
									    settings: {
									        theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
									            'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
									        theme_advanced_buttons2: null,
									        theme_advanced_buttons3: null,
									        theme_advanced_buttons4: null,
									        theme_advanced_statusbar_location: null
									    },
									    files_browser_window_url: false
									});

									editor = new tinyMceWysiwygSetup(
									    'description',
									    config
									);

									editor.turnOn();

									jQuery('#description')
								    .addClass('wysiwyg-editor')
								    .data(
								        'wysiwygEditor',
								        editor
								    );
								});
								</script> */ ?>
								<script>
									require([
										"jquery",
										"mage/translate",
										"mage/adminhtml/events",
										"mage/adminhtml/wysiwyg/tiny_mce/setup"
									], function(jQuery){
										wysiwygcompany_description = new wysiwygSetup("description", {
											"width":"99%",  // defined width of editor
											"height":"200px", // height of editor
											"plugins":[{"name":"image"}], // for image
											"tinymce4":{"toolbar":"formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link table charmap","plugins":"advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
											}
										});
										wysiwygcompany_description.setup("exact");
									});
								</script>
						</div>
					</div>
					<?php

					$mp_pro_status = 0;
					$mp_pro_coll = $helper->getSellerProductDataByProductId($product_id);
					foreach ($mp_pro_coll as $key => $value) {
						$mp_pro_status = $value['status'];
					}
					if(!$helper->getIsProductEditApproval() && $mp_pro_status==1 || !$helper->getIsProductApproval() && !$helper->getIsProductEditApproval() ){ ?>
						<div class="field required">
							<label class="label"><?php echo __('Status') ?>:</label>
							<?php
							if($product_hint_status && $helper->getProductHintEnable()){?>
								<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintStatus() ?>"/>
							<?php
							} ?>
							<div class="control">
								<input type="radio" name="status" id="status" value="1" <?php if($product_coll->getStatus()==1){ echo 'checked="checked"'; } ?>/><?php echo __("Enable"); ?><br>
								<input type="radio" name="status" id="status" value="2" <?php if($product_coll->getStatus()==2){ echo 'checked="checked"'; } ?>/><?php echo __("Disable"); ?>
							</div>
						</div>
					<?php
					} ?>
					<div class="field required">
						<label class="label"><?php echo __('SKU') ?>:</label>
						<?php
						if($product_hint_status && $helper->getProductHintSku()){?>
							<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintSku() ?>"/>
						<?php
						} ?>
						<div class="control">
							<input name="product[sku]" id="sku" class="required-entry input-text" type="text" value="<?php  echo $product_coll->getsku(); ?>"/>
						</div>
						<div id="skuavail" >
							<span class="success-msg skuavailable"><?php echo __('SKU Available') ?></span>
						</div>
						<div id="skunotavail" >
							<span class="error-msg skunotavailable"><?php echo __('SKU Already Exist') ?></span>
						</div>
					</div>
					<div class="field required <?php if($product_coll['type_id']=='configurable'){ ?> no-display <?php } ?>">
						<label class="label"><?php echo __('Price') ?><b><?php echo  " (".$currency_symbol.")"; ?></b>:</label>
						<?php
						if($product_hint_status && $helper->getProductHintPrice()){?>
							<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintPrice() ?>"/>
						<?php
						} ?>
						<div class="control">
							<input type="text" class="required-entry validate-zero-or-greater input-text" name="product[price]" id="price" value="<?php echo $product_coll->getPrice() ?>" data-ui-id="product-tabs-attributes-tab-fieldset-element-text-product-price"/>
						</div>
					</div>
					<?php if($product_coll['type_id']!='configurable'){ ?>
						<div class="field">
							<label class="label"><?php echo __('Special Price') ?><b><?php echo  " (".$currency_symbol.")"; ?></b>:</label>
							<?php
							if($product_hint_status && $helper->getProductHintSpecialPrice()){?>
								<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintSpecialPrice() ?>"/>
							<?php
							} ?>
							<div class="control">
								<input type="text" class="widthinput input-text validate-zero-or-greater" name="product[special_price]" id="special-price" value="<?php echo $product_coll->getSpecialPrice() ?>"/>
							</div>
						</div>
						<div class="field">
							<label class="label"><?php echo __('Special Price From') ?>:</label>
							<?php
							if($product_hint_status && $helper->getProductHintStartDate()){?>
								<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintStartDate() ?>"/>
							<?php
							} ?>
							<?php 
							if($product_coll->getData('special_from_date')){
								$special_from_date = $block->formatDate($product_coll->getData('special_from_date')); 
							}else{
								$special_from_date = '';
							} ?>
							<div class="control">
								<input type="text" name="product[special_from_date]" id="special-from-date" class="input-text" value="<?php echo $special_from_date; ?>"/>
							</div>
						</div>
						<div class="field">
							<label class="label"><?php echo __('Special Price To') ?>:</label>
							<?php
							if($product_hint_status && $helper->getProductHintEndDate()){?>
								<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintEndDate() ?>"/>
							<?php
							} ?>
							<?php 
							if($product_coll->getData('special_to_date')){
								$special_to_date = $block->formatDate($product_coll->getData('special_to_date')); 
							}else{
								$special_to_date = '';
							} ?>
							<div class="control">
								<input type="text" name="product[special_to_date]" id="special-to-date" class="input-text" value="<?php echo $special_to_date; ?>" />
							</div>
						</div>
					<?php
					} ?>
					<input id="inventory_manage_stock" type="hidden" name="product[stock_data][manage_stock]" value="<?php echo $product_coll['stock_data']['manage_stock']?>">
					<input type="hidden" value="1" name="product[stock_data][use_config_manage_stock]" id="inventory_use_config_manage_stock">
					<div class="field required">
						<label class="label"><?php echo __('Stock') ?>:</label>
						<?php
						if($product_hint_status && $helper->getProductHintQty()){?>
							<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintQty() ?>"/>
						<?php
						} ?>
						<div class="control">
							<input type="text" class="required-entry validate-number input-text" name="product[quantity_and_stock_status][qty]" id="qty" value="<?php echo $product_coll['quantity_and_stock_status']['qty'] ?>"/>
						</div>
					</div>
					<div class="field required">
						<label class="label"><?php echo __('Stock Availability') ?>:</label>
						<?php
						if($product_hint_status && $helper->getProductHintStock()){?>
							<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintStock() ?>"/>
						<?php
						} ?>
						<?php
						$is_in_stock = $product_coll['quantity_and_stock_status']['is_in_stock'];
						?>
						<div class="control">
							<select id="" class="select" name="product[quantity_and_stock_status][is_in_stock]">
								<option <?php if($is_in_stock==1) echo "selected"; ?> value="1"><?php echo __("In Stock"); ?></option>
								<option <?php if($is_in_stock==0) echo "selected"; ?> value="0"><?php echo __("Out of Stock"); ?></option>
							</select>
						</div>
					</div>
					<div class="field required">
						<label class="label"><?php echo __('Visibility') ?>:</label>
						<div class="control">
							<select id="visibility" class=" required-entry required-entry select" name="product[visibility]">
								<option value=""><?php echo __('Please Select')?></option>
								<?php
								$product_visibility = $helper->getVisibilityOptionArray();
								foreach($product_visibility as $key=>$value){
									?>
									<option value="<?php echo $key ?>" <?php if($key==$product_coll->getVisibility()){ echo "selected='selected'";}?>><?php echo $value?></option>
								<?php 
								} ?>
							</select>
						</div>
					</div>
					<?php 
						$shopUrl = '';
						$cusId = $objectManager->get('\Magento\Customer\Model\Session')->getCustomerId(); 
						$collection = $objectManager->create('Webkul\Marketplace\Model\Seller')
							->getCollection()
							->addFieldToFilter('seller_id',$cusId);
							foreach($collection as  $partnerData){
								
							}
						//echo "<pre>"; print_r($partnerData->getShopUrl()); exit;
						$shopUrl = $partnerData->getShopUrl();
					?>
					<div class="field" style="display:none;">
						<label class="label"><?php echo __('Vendor') ?>:</label>
						<div class="control">
							<input type="text" name="product[shopurl]" id="shopurl" value="<?php echo $shopUrl ?>"/>
						</div>
					</div>
					
					<div class="field required">
						<label class="label"><?php echo __('Barcode') ?>:</label>
						<div class="control">
							<input type="text" name="product[barcode]" id="barcode" class="input-text required-entry" value="<?php echo $product_coll->getBarcode() ?>" />
						</div>
					</div>
					<div class="field required" style="display:none;">
						<label class="label"><?php echo __('Tax Class') ?>:</label>
						<?php
						if($product_hint_status && $helper->getProductHintTax()){?>
							<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintTax() ?>"/>
						<?php
						} ?>
						<div class="control">
							<select id="tax-class-id" class=" required-entry required-entry select" name="product[tax_class_id]">
								<option value="0"><?php echo __('None')?></option>
								<?php
								$taxid=$product_coll->getData('tax_class_id');
								$taxes=$helper->getTaxClassModel();
								foreach($taxes as $tax){
									?>
									<option <?php echo $taxid==$tax->getId()? 'selected':''; ?> value="<?php echo $tax->getId() ?>"><?php echo $tax->getClassName()?></option>
								<?php 
								} ?>
							</select>
						</div>
					</div>
					<div class="field" style="display:none;">
						<label class="label"><?php echo __('Weight') ?>:</label>
						<?php
						if($product_hint_status && $helper->getProductHintWeight()){?>
							<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/quest.png'); ?>" class='questimg' title="<?php echo $helper->getProductHintWeight() ?>"/>
						<?php
						} ?>
						<div data-role="weight-switcher">
							<label data-ui-id="product-tabs-attributes-tab-element-radios-product-product-has-weight-label" for="weight-switcher">
								<span><?php echo __('Does this have a weight?')?></span>
							</label>
							<div class="control">
								<div class="control">
									<input type="radio" <?php if($product_coll['type_id']=='simple' || $product_coll['type_id']=='configurable'){ ?>checked="checked" <?php } ?> class="weight-switcher" id="weight-switcher1" value="1" name="product[product_has_weight]">
									<label for="weight-switcher1">
										<span><?php echo __('Yes')?></span>
									</label>
								</div>
								<div class="control">
									<input disabled="disabled" type="radio" <?php if($product_coll['type_id']=='downloadable'||$product_coll['type_id']=='virtual'){ ?>checked="checked" <?php } ?> class="weight-switcher" id="weight-switcher0" value="0" name="product[product_has_weight]">
									<label for="weight-switcher0">
										<span><?php echo __('No')?></span>
									</label>
								</div>
							</div>
						</div>
						<div class="control">
							<input type="text" class="validate-number validate-zero-or-greater validate-number-range number-range-0-99999999.9999 input-text" name="product[weight]" id="weight" value="<?php echo $product_coll->getWeight();?>" <?php if($product_coll['type_id']=='downloadable'||$product_coll['type_id']=='virtual'){ ?>disabled="disabled" <?php } ?>/>
						</div>
					</div>
					<?php echo $block->getChildHtml(); ?>			
				</fieldset>
			</div>		
		</form>
		<div class="buttons-set">
			<p class="required">* <?php echo __('Required Fields') ?></p>		
			<p class="back-link">
				<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php echo __('Back') ?></a>
			</p>
		</div>
		<script>
		    require([
		        "jquery",
		        "mage/mage",
	        	'mage/calendar'
		    ], function($){
		        var dataForm = $('#edit-product');
		        dataForm.mage('validation', {});
		        <?php if($product_coll['type_id']!='configurable'){ ?>
			        $("#special-from-date").calendar({'dateFormat':'mm/dd/yy'});
					$("#special-to-date" ).calendar({'dateFormat':'mm/dd/yy'});
				<?php
				} ?>
		        var i=2;

		        $('#save-btn').click(function(e){
					if($("#edit-product").valid()!=false){
						if($('#description_ifr').length){
							var desc = $('#description_ifr').contents().find('#tinymce').text(); 
							$('#description-error').remove();
							if(desc=="" || desc==null){
								$('#description-error').remove();
								$('#description').parent().append('<div class="mage-error" generated="true" id="description-error">This is a required field.</div>');
							}
							if(desc!="" && desc!=null){ 
								$('#save-btn span span').text('<?php echo __("Saving")?>..');
								$('.button').css('opacity','0.7'); 
								$('.button').css('cursor','default'); 
								$('.button').attr('disabled','disabled'); 
								$('#edit-product').submit(); 
							}else{
								return false;
							}
						}
					}
				});
				
				$('.input-text').change(function(){
					var validt = $(this).val();
					var regex = /(<([^>]+)>)/ig;
					var mainvald = validt .replace(regex, "");
					$(this).val(mainvald);	
			    });

				$('input#sku').change(function(){
					var len=$('input#sku').val();
					var len2=len.length;
					if(len2==0){
						alert('<?php echo __("SKU can\'t be left empty")?>');
						$('div#skuavail').css('display','none');
						$('div#skunotavail').css('display','none');
					}
					else{
						$.ajax({
							url: "<?php echo $block->getUrl('marketplace/product/verifysku', ['_secure' => $this->getRequest()->isSecure()]);?>",
							type: "POST",
							data: {sku:$('input#sku').val()},
							dataType: 'html',
							success:function($data){
								$data=JSON.parse($data);
								if($data.avl==1){
									$('div#skuavail').css('display','block');
									$('div#skunotavail').css('display','none');
								}
								else{
									$('div#skunotavail').css('display','block');
									$('div#skuavail').css('display','none');
									$("input#sku").attr('value','');
								}
							}
						});
					}
				});

				$('body').on('change','.wk-elements',function(){
					var category_id=$(this).val();					
					if(this.checked == true){
						var $obj = $('<input/>').attr('type','hidden').attr('name','product[category_ids][]').attr('id','wk-cat-hide'+category_id).attr('value',category_id);
						$('.wk-for-validation').append($obj);
					}else{
						$('#wk-cat-hide'+category_id).remove();
					}
				});

				$("#wk-bodymain").delegate('.wk-plus ,.wk-plusend,.wk-minus, .wk-minusend ',"click",function(){
					var thisthis=$(this);	
					if(thisthis.hasClass("wk-plus") || thisthis.hasClass("wk-plusend")){
						if(thisthis.hasClass("wk-plus"))
							thisthis.removeClass('wk-plus').addClass('wk-plus-click');
						if(thisthis.hasClass("wk-plusend"))
							thisthis.removeClass('wk-plusend').addClass('wk-plusend-click');
						thisthis.prepend("<span class='wk-node-loader'></span>");
						$.ajax({
							url  	:   "<?php echo $block->getUrl('marketplace/product/categorytree/', ['_secure' => $this->getRequest()->isSecure()]);?>",
							type 	:   "POST",
							data 	:   {CID:thisthis.siblings("input").val(),
										ML:thisthis.parent(".wk-cat-container").css("margin-left").replace("px",""),
										CATS : 	"<?php echo implode(',',$categories); ?>"},
							dataType:   "html",
							success :   function(content){
								var newdata=  $.parseJSON(content);
								len= newdata.length;
								var pxl= parseInt(thisthis.parent(".wk-cat-container").css("margin-left").replace("px",""))+20;
								thisthis.find(".wk-node-loader").remove();
								if(thisthis.attr("class") == "wk-plus")
									thisthis.attr("class","wk-minus");
								if(thisthis.attr("class") == "wk-plusend")
									thisthis.attr("class","wk-minusend");
								if(thisthis.attr("class") == "wk-plus-click")
									thisthis.attr("class","wk-minus");
								if(thisthis.attr("class") == "wk-plusend-click")
									thisthis.attr("class","wk-minusend");
							     for(i=0;i<len; i++){ 
									id=newdata[i].id;
									checkn=newdata[i].check;
									nam=newdata[i].name;
									if(checkn==1){														 
										if(newdata[i].counting ==0){
											thisthis.parent(".wk-cat-container").after('<div class="wk-removable wk-cat-container" style="display:none;margin-left:'+pxl+'px;"><span  class="wk-no"></span><span class="wk-foldersign"></span><span class="wk-elements wk-cat-name">'+ nam +'</span><input class="wk-elements" type="checkbox" checked value='+ id+' </div>');
										}else{
											thisthis.parent(".wk-cat-container").after('<div class="wk-removable wk-cat-container" style="display:none;margin-left:'+pxl+'px;"><span  class="wk-plusend"></span><span class="wk-foldersign"></span><span class="wk-elements wk-cat-name">'+ nam +'</span><input class="wk-elements" type="checkbox" checked value='+ id +'></div>');   
										}
									}else{
										if(newdata[i].counting ==0){
											thisthis.parent(".wk-cat-container").after('<div class="wk-removable wk-cat-container" style="display:none;margin-left:'+pxl+'px;"><span  class="wk-no"></span><span class="wk-foldersign"></span><span class="wk-elements wk-cat-name">'+ nam +'</span><input class="wk-elements" type="checkbox" value='+ id+'></div>');
										}else{
											thisthis.parent(".wk-cat-container").after('<div class="wk-removable wk-cat-container" style="display:none;margin-left:'+pxl+'px;"><span  class="wk-plusend"></span><span class="wk-foldersign"></span><span class="wk-elements wk-cat-name">'+ nam +'</span><input class="wk-elements" type="checkbox" value='+ id +'></div>');   
										}
									}
								}	
								thisthis.parent(".wk-cat-container").nextAll().slideDown(300);
							}
						});			
					}
					if(thisthis.hasClass("wk-minus") || thisthis.hasClass("wk-minusend")){
						if(thisthis.attr("class") == "wk-minus")
							thisthis.attr("class","wk-plus");
						if(thisthis.attr("class") == "wk-minusend")
							thisthis.attr("class","wk-plusend");
						var thiscategory = thisthis.parent(".wk-cat-container");
						var marg= parseInt(thiscategory.css("margin-left").replace("px",""));
						while(thiscategory.next().hasClass("wk-removable")){
						  
						if(parseInt(thiscategory.next().css("margin-left").replace("px",""))>marg)
							thiscategory.next().slideUp("slow",function(){$(this).remove();});
							thiscategory = thiscategory.next();	
							if(typeof thiscategory.next().css("margin-left")!= "undefined"){
								if( marg==thiscategory.next().css("margin-left").replace("px",""))
								{
								  break;
								}
							}
						}
					}		
				});
		    });
	    </script>
	    <script type='text/javascript'>
            require(['jquery', 'prototype', 'domReady!'], function($) {
                var qty = $('#qty'),
                    productType = $('#product_type_id').val(),
                    stockAvailabilityField = $('#quantity_and_stock_status'),
                    manageStockField = $('#inventory_manage_stock'),
                    useConfigManageStockField = $('#inventory_use_config_manage_stock'),
                    fieldsAssociations = {
                        'qty': 'inventory_qty',
                        'quantity_and_stock_status': 'inventory_stock_availability'
                    };

                var qtyDefaultValue = qty.val();
            })
        </script>
        <script>
			require([
			    "jquery",
			    "Webkul_Marketplace/catalog/type-events"
			], function($, TypeSwitcher){
			    var $form = $('[data-form=edit-product]');
			    $form.data('typeSwitcher', TypeSwitcher.init());
			});
		</script>
	    <script type="text/x-magento-init">
		    {
		        "*": {
		            "Webkul_Marketplace/js/product/weight-handler": {},
		            "Webkul_Marketplace/catalog/apply-to-type-switcher": {}
		        }
		    }
		</script>
	<?php
	}else{
		echo "<h2 class='wk-mp-error_msg'>".__("You are not authorize to edit this product.")."</h2>";
	}
}else{ ?>
	<h2 class="wk-mp-error_msg">
		<?php echo __("To Become Seller Please Contact to Admin."); ?>
	</h2>
	<?php
} ?>
