<?php

$objectManager =    \Magento\Framework\App\ObjectManager::getInstance();
$_productCollection     =   $block->_getProductCollection();

?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php 
        /** @var $_product \Magento\Catalog\Model\Product */ 
        $pos = $block->getPositioned();

        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $iterator = 1;
    ?>
    <?php foreach ($_productCollection as $_product): ?>
        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product">' : '</li><li class="item product">' ?>
        <div class="product-item-info" data-container="product-grid">
            <?php
            $productImage = $block->getImage($_product, $image);
            if ($pos != null) {
                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                    . 'top:' . $productImage->getHeight() . 'px;"';
            }
            ?>
            <?php // Product Image ?>
            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                <?php echo $productImage->toHtml();

                 $RatingOb  =   $objectManager->get("Magento\Review\Model\ReviewFactory");

                $RatingOb->create()->getEntitySummary($_product, 1);
              ?>
            </a>
            <div class="product details product-item-details">
                <?php
                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                ?>
                <strong class="product name product-item-name">
                    <a class="product-item-link"
                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                    </a>
                </strong>
                <?php 
                $_formattedActualPrice = (isset($_product->getData()["price"])?$_product->getData()["price"]:$block->getProductPrice($_product));

                $_formattedSpecialPrice = $_product->getFinalPrice();

                if($_formattedActualPrice>$_formattedSpecialPrice){ ?>
                    <span><?php echo round((($_formattedActualPrice-$_formattedSpecialPrice)/$_formattedActualPrice)*100, 2);  ?>% Off</span>
                <?php } ?>
                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                <?php echo $block->getProductDetailsHtml($_product); ?>
                <div class="product-item-inner">
                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>

                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                            <?php if ($_product->isSaleable()): ?>

                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                <a href="#"
                                   class="action towishlist fa fa-heart-o"
                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                   data-action="add-to-wishlist"
                                   role="button">
                                    <!-- <span><?php /* @escapeNotVerified */ //echo __('Add to Wish List') ?></span> -->
                                </a>
                            <?php endif; ?>

                            
                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                    <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit"
                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                            class="action tocart  fa fa-shopping-cart">
                                        <?php /* @escapeNotVerified */ //echo __('Add to Cart') ?>
                                    </button>
                                </form>
                             <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
                               class="fa fa-search"
                               title="<?php echo $block->escapeHtml(__('View Item')); ?>"
                               aria-label="<?php echo $block->escapeHtml(__('View Item')); ?>"
                               role="button">
                            </a>
                           
                            <?php else: ?>
                                <?php if ($_product->getIsSalable()): ?>
                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                <?php else: ?>
                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                        
                    </div>
                    <?php if ($showDescription):?>
                        <div class="product description product-item-description">
                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                               class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
    <?php endforeach; ?>
<?php endif; ?>