<?php
$partner=array();
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
//$partner=$block->getProfileDetail();
//$seller_id=$partner['seller_id']; 
$objectManager =    \Magento\Framework\App\ObjectManager::getInstance();

?>
<?php 
    
    $_productCollection     =   $block->_getProductCollection();
    ?>
   

    <!-- Left categories -->
    <?php //echo $this->getLayout()->createBlock("Webkul\Marketplace\Block\Sellercategory")->setTemplate("Webkul_Marketplace::sellerproductscategory.phtml")->toHtml();?>

    <div class="wk_mp_design main_section">
        <div class="main_recomend" <?php if( !empty($_productCollection) ) { echo 'style="padding: 0;"';}?>>
            <?php
            $_helper = $this->helper('Magento\Catalog\Helper\Output');
            ?>
            <?php if ( !empty($_productCollection) ): ?>
                <?php //echo $block->getToolbarHtml() ?>
                <?php //echo $block->getAdditionalHtml() ?>
                <?php
                //if ($block->getMode() == 'grid') {
                    $viewMode = 'grid';
                    $image = 'category_page_grid';
                    $showDescription = false;
                    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                /*} else {
                    $viewMode = 'list';
                    $image = 'category_page_list';
                    $showDescription = true;
                    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
                }*/
                /**
                 * Position for actions regarding image size changing in vde if needed
                 */
                $pos = $block->getPositioned();
                ?>
                <div class="products products_wrapper wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
                    <h3><?php echo __("New products from followed stores") ?></h3>
                    <?php $iterator = 1; ?>
                    <ol id="followedstoreproducts_carousal" class="products list items product-items">
                        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                        <?php foreach ($_productCollection as $_product): ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product">' : '</li><li class="item product">' ?>
                            <div class="product-item-info" data-container="product-grid">
                                <?php
                                $productImage = $block->getImage($_product, $image);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>
                                <?php // Product Image ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?php echo $productImage->toHtml();

                                     $RatingOb  =   $objectManager->get("Magento\Review\Model\ReviewFactory");

                                    $RatingOb->create()->getEntitySummary($_product, 1);
                                  ?>
                                </a>
                                <div class="product details product-item-details">
                                    <?php
                                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
                                    <?php 
                                    $_formattedActualPrice = (isset($_product->getData()["price"])?$_product->getData()["price"]:$block->getProductPrice($_product));

                                    $_formattedSpecialPrice = $_product->getFinalPrice();

                                    if($_formattedActualPrice>$_formattedSpecialPrice){ ?>
                                        <span><?php echo round((($_formattedActualPrice-$_formattedSpecialPrice)/$_formattedActualPrice)*100, 2);  ?>% Off</span>
                                    <?php } ?>
                                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>
                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>

                                            <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                <?php if ($_product->isSaleable()): ?>

                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#"
                                                       class="action towishlist fa fa-heart-o"
                                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist"
                                                       role="button">
                                                        <!-- <span><?php /* @escapeNotVerified */ //echo __('Add to Wish List') ?></span> -->
                                                    </a>
                                                <?php endif; ?>

                                                
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                                        <?php echo $block->getBlockHtml('formkey')?>
                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart  fa fa-shopping-cart">
                                                            <?php /* @escapeNotVerified */ //echo __('Add to Cart') ?>
                                                        </button>
                                                    </form>
                                                 <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
                                                   class="fa fa-search"
                                                   title="<?php echo $block->escapeHtml(__('View Item')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('View Item')); ?>"
                                                   role="button">
                                                </a>

                                                <!-- <div data-role="add-to-links" class="actions-secondary"<?php //echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>> -->
                                                    <?php
                                                    //$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                    ?>
                                                    <!-- <a href="#"
                                                       class="action tocompare"
                                                       title="<?php //echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                       aria-label="<?php //echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */ //echo $compareHelper->getPostDataParams($_product); ?>'
                                                       role="button">
                                                        <span><?php /* @escapeNotVerified */ //echo __('Add to Compare') ?></span>
                                                    </a> -->
                                               <!--  </div> -->
                                               
                                                <?php else: ?>
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                            
                                        </div>
                                        <?php if ($showDescription):?>
                                            <div class="product description product-item-description">
                                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                                   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                        <?php endforeach; ?>
                    </ol>
                    <?php if(count($_productCollection) > 2 ){ ?>
                    <div class="carousal_control">
                        <a id="salecarousal_pre" class="prev" href="#"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
                        <a id="salecarousal_next" class="next" href="#"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
                    </div>
                    <?php } ?>
                </div>
                <?php //echo $block->getToolbarHtml() ?>
                <?php if (!$block->isRedirectToCartEnabled()) : ?>
                    <script type="text/x-magento-init">
                    {
                        "[data-role=tocart-form], .form.map.checkout": {
                            "catalogAddToCart": {}
                        }
                    }
                    </script>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>

<script type="text/javascript">
    require(['jquery', 'bootstrap', 'carouFredSel'],function($, bootstrap, carouFredSel){
        $(document).ready(function() {
            $('#followedstoreproducts_carousal').carouFredSel({
                // responsive: true,
                width: '100%',
                scroll: 1,
                prev: '#salecarousal_pre',
                next: '#salecarousal_next',
                items: {
                    height: 'auto'
                }
            });

        });
    });
</script>