<?php 
$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$isPartner= $helper->isSeller();
if($isPartner==1){
	$filter = '';
	$filter_status = '';
	$filter_date_frm = '';
	$filter_date_to = '';
	if(isset($_GET['s'])){
        $filter = $_GET['s'] != ""?$_GET['s']:"";
	}
	if(isset($_GET['status'])){
        $filter_status = $_GET['status'] != ""?$_GET['status']:"";
	}
	if(isset($_GET['from_date'])){
        $filter_date_frm = $_GET['from_date'] != ""?$_GET['from_date']:"";
	}
	if(isset($_GET['to_date'])){
        $filter_date_to = $_GET['to_date'] != ""?$_GET['to_date']:"";
	}
	$_products_coll = $block->getAllProducts(); ?>	
	<div class="wk-mp-design">
		<fieldset class="fieldset info wk-mp-fieldset product_list_table">
			<div class="page_new_button_content">
			    <div class="pagetitle">
			        <span><?php echo __('Product List') ?></span>
			    </div>
			    <div class="add_button">
			        <a href="<?php echo $block->getUrl('marketplace/product/create/'); ?>">
			    	    <span><?php echo __('Add New Poduct') ?></span>
			    	</a>
			    </div>
			</div>
			<div class="grid">
				<div class="hor-scroll">
					<form action="<?php echo $block->getUrl('marketplace/product/productlist', ['_secure' => $this->getRequest()->isSecure()])?>" method="get" id="form-productlist-filter"  name="formProductlistFilter">
						 <div class="no-more-tables">
							<table cellspacing="0" class="border wk-mp-list-table">
							    <thead>
							        <tr id="wk-mp-tr-heading">
							            <th><span><?php echo __('Product Name') ?></span></th>
							            <th><span><?php echo __('Date') ?></span></th>
							            <th><span><?php echo __('Product Status') ?></span></th>
							            <th><span>&nbsp;</span></th>
							        </tr>
							    </thead>
							    <tbody class="wk-mp-body">
							    	<tr>
							    		<td  data-title="Product Name">
							    			<input type="text" class="input-text" name="s" placeholder='<?php echo __('Search by product name') ?>' value="<?php echo $filter?>"/>
							    		</td>
							    		<td data-title="Date">
							    			<span class="wk-mp-td-span">
							    				<?php echo __('From:') ?>
							    				<input name="from_date" id="special-from-date" class="input-text" value="<?php echo $filter_date_frm?>" />
							    			</span>				    			
							    			<span class="wk-mp-td-span">
							    				<?php echo __('To:') ?>
							    				<input name="to_date" id="special-to-date" class="input-text" value="<?php echo $filter_date_to?>" />
							    			</span>
							    		</td>
							    		<td data-title="Status">
						    				<select name="status" class="input-text">
						    					<option value=""><?php echo __('All') ?></option>
							    				<option value="1" <?php if($filter_status == 1) echo 'selected="selected"'?>>
							    					<?php echo __('Approved') ?>
							    				</option>
							    				<option value="2" <?php if($filter_status == 2) echo 'selected="selected"'?>>
							    					<?php echo __('Unapproved') ?>
							    				</option>
							    			</select>
							    		</td>
							    		<td data-title="">
							    			<button class="button btn btn-lg btn-primary" title="Save" type="submit">
												<span><?php echo __('Submit') ?></span>
											</button>
							    		</td>
							    	</tr>
							    </tbody>
							</table>
						</div>
					</form>
					<?php if ($_products_coll && count($_products_coll)): ?>
						<form action="<?php echo $block->getUrl('marketplace/product/massDelete', ['_secure' => $this->getRequest()->isSecure()]) ?>" method="post" id="form-productlist-massdelete" name="formProductlistMassdelete">
							<?php echo $block->getBlockHtml('formkey')?>
							<?php
								/*<button class="button btn btn-info" title="<?php echo __('Delete Products') ?>" type="submit" id="mass-delete-butn">
								<span><span><?php echo __('Delete Products') ?></span></span>
							</button>*/
							?>
							<div class="table-responsive">
								<table  cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table" style="color:black;">
								    <thead>
								        <tr class="wk-content">
								        	<th class="wk-check-first-td">
								    			<span>
													<input type="checkbox" name="mpselecctall" value="all" id="mpselecctall"/>
												</span>
								    		</th>
								    		<th class="wk-first-td">
								    			<span class="name">
													<?php echo __('Product')?>
												</span>
								    		</th>
								    		<th>
								    			<span class="pro-status">
													<?php echo __('Type')?>
												</span>
								    		</th>
								    		<th>
								    			<span class="pro-status">
													<?php echo __('Status')?>
												</span>
								    		</th>
								    		<th class="wk-list-th-display">
								    			<span class="qty"><?php echo __('Qty. Confirmed')?></span>
								    			
								    		</th>
								    		<th class="wk-list-th-display">
								    			<span class="qty">
													<?php echo __('Qty. Pending')?>
												</span>
								    		</th>	
								    		<th class="wk-list-th-display">
								    			<span class="qty">
													<?php echo __('Qty. Sold')?>
												</span>
								    		</th>
								    		<th class="wk-list-th-display1">
								    			<span >
													<?php echo __('Earn Amount')?>
												</span>
								    		</th>
								    		<th class="wk-list-th-display1">
								    			<span>
													<?php echo __('Action')?>
												</span>
								    		</th>		    		
								    	</tr>
								    </thead>
								    <tbody>
								    	<?php 
								    	$i = 0;
										foreach($block->getAllProducts() as $products){
											$i++;
							            	$image_url = $block->imageHelperObj()->init($products, 'product_page_image_small')
								                        ->setImageFile($products->getFile())
								                        ->getUrl();
								            $salesdetail=$block->getSalesdetail($products->getEntityId());
											$quantity 	=	$StockState->getStockQty($products->getId(), $products->getStore()->getWebsiteId());
											?>
									    	<tr class="wk-row-view <?php echo $class = ($i == count($block->getAllProducts()))? 'wk-last_tr':''?>">
									    		<td class="wk-check-first-td">
									    			<span>
														<input type="checkbox" name="product_mass_delete[]" class="mpcheckbox" value="<?php echo $products->getEntityId(); ?>"/>
													</span>
									    		</td>
									    		<td class="wk-first_td">
													<input type="hidden" class="hidden-id" value="<?php echo $products->getEntityId(); ?>" />
													<div class="name" title="<?php echo $products->getName(); ?>">
														<div class="wk-pro-divide1">
															<img src="<?php echo $image_url?>" class="image" />
														</div>
														<div class="wk-pro-divide2">
															<div style="width:100%;">
																<?php if($products->getStatus()==1 && $products->getVisibility()!=1) { ?>
																	<a href="javascript:void(0)<?php /*echo $products->getProductUrl() */ ?>" target="blank">
																<?php }?>
																	<?php echo $products->getName();?>
																<?php if($products->getStatus()==1 && $products->getVisibility()!=1) { ?>
																	</a>
																<?php }?>
																<br>
																<?php 
																echo "<strong>SKU</strong>: ".$products->getSku();
																echo "<br/><strong>Barcode</strong>: ".$products->getData('barcode');
																// echo "<br/><strong>Quantity</strong>: ".$products->getQty();
																// echo "<pre>";
																// print_r($products->getData());die;
																?>	
															</div>
															<div style="width:100%;float:left;">
																<?php 
																if($products->getPrice()*1){
																	echo $products->getFormatedPrice();
																}else{
																	echo $helper->getCurrencySymbol().'0.00';
																}
																?>
															</div>
														</div>
													</div>
									    		</td>
									    		<td>		
													<span class=" pro-status">
														<?php echo __($products->getTypeId())?>
													</span>
												</td>
									    		<?php 
									    		if($products->getStatus()==2) {	?>
									    			<td>		
														<span class=" pro-status">
															<?php echo __('Pending')?>
														</span>
													</td>
													<td class="wk-list-th-display">
														<span class=" qty">
															<?php echo __('Pending')?>
														</span>
													</td>
													<td class="wk-list-th-display">
														<span class=" qty">
															<?php echo __('Pending')?>
														</span>	
													</td>
													<td class="wk-list-th-display">
														<span class=" qty">
															<?php echo __('Pending')?>
														</span>	
													</td>
													<td class="wk-list-th-display1">
														<span class=" qty">
															<?php echo __('Pending')?>
														</span>	
													</td>									
												<?php }
												else{ ?>
													<td>		
														<span class=" pro-status">
															<?php echo __('Approved')?>
														</span>
													</td>
												    <td class="wk-list-th-display">
												    	<span class=" qty">
												    		<?php echo $quantity; ?>
												    	</span>	
												    </td>
												    <td class="wk-list-th-display1">
												    	<span class=" qty">
												    		<?php echo $salesdetail['quantitysold']; ?>
												    	</span>	
												    </td>
												    <td class="wk-list-th-display">
												    	<span class=" price">
												    		<?php echo $salesdetail['amountearned']; ?>
												    	</span>	
												    </td>
												    <td class="wk-list-th-display">
												    	<span class=" price">
												    		<?php echo $salesdetail['amountearned']; ?>
												    	</span>	
												    </td>
												<?php } ?>		
												<td>
									    			<span class="label wk-action">
														<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/icon-edit.png'); ?>" data-url="<?php echo $block->getUrl('marketplace/product/edit', ['id'=>$products->getId(), '_secure' => $this->getRequest()->isSecure()])?>" alt="<?php echo __('Edit')?>" title="<?php echo __('Edit')?>" class="mp-edit"/>
														<img src="<?php echo $this->getViewFileUrl('Webkul_Marketplace::images/icon-trash.png'); ?>" alt="<?php echo __('Delete')?>" title="<?php echo __('Delete')?>" class="mp-delete" data-url="<?php echo $block->getUrl('marketplace/product/delete/', ['id'=>$products->getId(), '_secure' => $this->getRequest()->isSecure()]) ?>"/>
													</span>	
									    		</td>		    		
									    	</tr>
									    	<?php
									    }?>
								    </tbody>
								</table>
							</div>
						</form>						
					<?php else: ?>
						<div class="wk-emptymsg">
							<?php echo __('No Product Available') ?>
						</div>
					<?php endif ?>					
				</div>
			</div>
			<?php if ($block->getPagerHtml()): ?>
		        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
		    <?php endif ?>	
		</fieldset>	
		<div class="buttons-set">
			<p class="back-link">
				<a href="javascript:;" onclick="javascript: window.history.back();" class="left btn btn-sm btn-primary"><i class="fa fa-angle-double-left"></i> <?php echo __('Back') ?></a>
			</p>
		</div>
	</div>	
	<script>
	    require([
	        "jquery",
	        "mage/mage",
        	'mage/calendar',
	        'prototype',
	        'domReady!'
	    ], function($){
	        var productListDataForm = $('#form-productlist-filter');
	        productListDataForm.mage('validation', {});

	        var productListMassdeleteDataForm = $('#form-productlist-massdelete');
	        productListMassdeleteDataForm.mage('validation', {});

			$("#special-from-date").calendar({'dateFormat':'mm/dd/yy'});
			$("#special-to-date").calendar({'dateFormat':'mm/dd/yy'});

			$('body').delegate('.mp-edit','click',function(){
				var dicision=confirm('<?php echo __(" Are you sure you want to edit this product ? ")?>');
				if(dicision==true){			
					var $url=$(this).attr('data-url');
					window.location = $url;
				}
			});
			$('#mass-delete-butn').click(function(e){
				var flag =0;
				$('.mpcheckbox').each(function(){
					if (this.checked == true){
						flag =1;
					}
				});
				if (flag == 0){
					alert("<?php echo __(' No Checkbox is checked ') ?>");
					return false;
				}
				else{
					var dicisionapp=confirm('<?php echo __(" Are you sure you want to delete these product ? ")?>');
					if(dicisionapp==true){
						$('#form-customer-product-new').submit();
					}else{
						return false;
					}
				}
			});

		    $('#mpselecctall').click(function(event) {
		        if(this.checked) {
		            $('.mpcheckbox').each(function() {
		                this.checked = true;      
		            });
		        }else{
		            $('.mpcheckbox').each(function() {
		                this.checked = false;           
		            });         
		        }
		    });

			$('.mp-delete').click(function(){
				var dicisionapp=confirm('<?php echo __(" Are you sure you want to delete this product ? ")?>');
				if(dicisionapp==true){
					var $url=$(this).attr('data-url');
					window.location = $url;
				}
			});
		});    
	</script>
	<?php
}else{?>
	<h2 class="wk-mp-error_msg">
		<?php echo __("To Become Seller Please Contact Admin"); ?>
	</h2>
	<?php
} ?>
<style>
.page_new_button_content .add_button {
    float: right;
    text-align: center;
    border: 1px solid #FFF;
    padding: 10px 4px;
    background: #c43c4b !important;
    color: #fff;
}
.page_new_button_content .add_button:hover {
    border: 1px solid #c43c4b;
    background: #fff !important;
}
.page_new_button_content .add_button a {
    color: #fff;
    text-decoration: none;
    padding: 10px;
}
.page_new_button_content {
    border-bottom: 1px solid #c6c6c6;
    width: 100%;
    float: left;
    margin-bottom: 10px;
    padding: 0 0 10px 0;
}
.page_new_button_content .pagetitle {
    float: left;
}
.page_new_button_content .pagetitle span {
    font-size: 20px;
 }
</style>