<style>
<?php if($block->getLang()=="ar"){ ?>
	.wpwl-wrapper-cardNumber,wpwl-group{
            direction: ltr !important;
        }
<?php } ?>

<?php echo $block->getCss();?>
</style>
<script>
	
    var wpwlOptions = {
        locale: "<?php echo $block->getLang();?>",
        paymentTarget: "_top",
        style: "<?php echo $block->getStyle();?>"
    }
</script>
<script src="<?php echo $block->getFormUrl(); ?>"></script>
<form action="<?php echo $block->getShopperUrl(); ?>" class="paymentWidgets" data-brands="<?php echo $block->getPaymentBrand(); ?>"></form>
