<ul class="category-listing">
<li>
<a href="#"><figure><img src="images/catgroy-icon1.png" alt="image">
<img src="images/hover-catgroy-icon1.png" alt="image" class="hover-image">
</figure>
<strong>Grocery</strong></a>
</li>

<li>
<a href="#"><figure><img src="images/catgroy-icon2.png" alt="image">
<img src="images/hover-catgroy-icon2.png" alt="image" class="hover-image">
</figure>
<strong>Pet Care</strong></a>
</li>


<li>
<a href="#"><figure><img src="images/catgroy-icon3.png" alt="image">
<img src="images/hover-catgroy-icon3.png" alt="image" class="hover-image">
</figure>
<strong>Grocery</strong></a>
</li>


<li>
<a href="#"><figure><img src="images/catgroy-icon4.png" alt="image">
<img src="images/hover-catgroy-icon4.png" alt="image" class="hover-image">
</figure>
<strong>Bakeles  &amp; Deserts</strong></a>
</li>

<li>
<a href="#"><figure><img src="images/catgroy-icon5.png" alt="image">
<img src="images/hover-catgroy-icon5.png" alt="image" class="hover-image">
</figure>
<strong>Electronics</strong></a>
</li>

<li>
<a href="#"><figure><img src="images/catgroy-icon6.png" alt="image">
<img src="images/hover-catgroy-icon6.png" alt="image" class="hover-image">
</figure>
<strong>Alcohol</strong></a>
</li>


<li>
<a href="#"><figure><img src="images/catgroy-icon7.png" alt="image">
<img src="images/hover-catgroy-icon7.png" alt="image" class="hover-image">
</figure>
<strong>Beauty &amp; Wellness</strong></a>
</li>
<li>
<a href="#"><figure><img src="images/catgroy-icon8.png" alt="image">
<img src="images/hover-catgroy-icon8.png" alt="image" class="hover-image">
</figure>
<strong>Speciality Stores</strong></a>
</li>


<li>
<a href="#"><figure><img src="images/catgroy-icon9.png" alt="image">
<img src="images/hover-catgroy-icon9.png" alt="image" class="hover-image">
</figure>
<strong>Kids &amp; Baby</strong></a>
</li>


<li>
<a href="#"><figure><img src="images/catgroy-icon10.png" alt="image">
<img src="images/hover-catgroy-icon10.png" alt="image" class="hover-image">
</figure>
<strong>Medicines</strong></a>
</li>
</ul>